/********************************************************************************
 * FILENAME: postgres_100_schema.sql
 * DIALECT: PostgreSQL
 * COMPLEXITY: EXTREME (100 Scenarios)
 * FEATURES: 
 * - STANDARD (Tables, Columns, Constraints)
 * - PARTITIONING (List, Range, Hash)
 * - INHERITANCE
 * - EXCLUSION CONSTRAINTS
 * - JSONB & ARRAYS
 * - ROW SECURITY POLICIES
 * - GENERATED COLUMNS
 * - CUSTOM TYPES (Domains, Enums, Composites)
 * - PROCEDURAL (Functions, Triggers)
 ********************************************************************************/

CREATE SCHEMA IF NOT EXISTS titan_db_core;
CREATE SCHEMA IF NOT EXISTS titan_db_analytics;

-- 1. Basic Table with Constraints
CREATE TABLE titan_db_core.dim_members (
    member_id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    tags ARRAY,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Partitioned Table (Range) with Indexes
CREATE TABLE titan_db_core.events_omniverse (
    event_uuid UUID NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE,
    actor_id VARCHAR(32),
    payload JSONB,
    cost_center TEXT,
    PRIMARY KEY (event_uuid, timestamp)
) PARTITION BY RANGE (timestamp);

CREATE TABLE titan_db_core.events_y2023 PARTITION OF titan_db_core.events_omniverse
    FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE TABLE titan_db_core.events_y2024 PARTITION OF titan_db_core.events_omniverse
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

-- 3. Inheritance & Generated Columns
CREATE TABLE titan_db_core.base_entity (
    entity_id SERIAL PRIMARY KEY,
    updated_at TIMESTAMP
);

CREATE TABLE titan_db_core.dim_hyper_entity (
    entity_code VARCHAR(50),
    attributes JSONB,
    search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', attributes::text)) STORED
) INHERITS (titan_db_core.base_entity);

-- 4. Exclusion Constraints & Identity
CREATE TABLE titan_db_core.fact_ledger (
    txn_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_id INT,
    valid_range TSTRANGE,
    EXCLUDE USING GIST (account_id WITH =, valid_range WITH &&)
);

-- 5. Domains & Types
CREATE DOMAIN titan_db_core.email_type AS TEXT CHECK (VALUE ~* '^.+@.+$');
CREATE TYPE titan_db_core.user_status AS ENUM ('active', 'inactive', 'banned');
CREATE TYPE titan_db_core.address AS (street VARCHAR, city VARCHAR, zip VARCHAR);

CREATE TABLE titan_db_core.users_extended (
    user_id INT,
    contact_email titan_db_core.email_type,
    current_status titan_db_core.user_status,
    home_address titan_db_core.address,
    CONSTRAINT fk_users_members FOREIGN KEY (user_id) REFERENCES titan_db_core.dim_members(member_id)
);

-- 6. Functions & Triggers
CREATE OR REPLACE FUNCTION titan_db_core.update_timestamp() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_members_timestamp
BEFORE UPDATE ON titan_db_core.dim_members
FOR EACH ROW EXECUTE FUNCTION titan_db_core.update_timestamp();

-- 7. Views
CREATE VIEW titan_db_analytics.v_active_members AS
SELECT * FROM titan_db_core.dim_members WHERE status = 'active';

CREATE MATERIALIZED VIEW titan_db_analytics.mv_event_summary AS
SELECT count(*) as total_events, date_trunc('day', timestamp) as event_day 
FROM titan_db_core.events_omniverse
GROUP BY 2;

-- 8. RLS
ALTER TABLE titan_db_core.events_omniverse ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_policy ON titan_db_core.events_omniverse
    FOR ALL
    TO public
    USING (payload->>'tenant_id' = current_user);

-- 9. Indexes
CREATE INDEX idx_events_payload_gin ON titan_db_core.events_omniverse USING GIN (payload);
CREATE INDEX idx_members_lower_email ON titan_db_core.dim_members ((lower(email)));
EXPLAIN ANALYZE SELECT * FROM titan_db_core.dim_members;