-- Migration Script for oracle
CREATE OR REPLACE PACKAGE ORDER_MGMT AS PROCEDURE PROCESS(ID NUMBER);
ALTER TABLE "orders" MODIFY "id" DECIMAL NOT NULL;
ALTER TABLE "orders" MODIFY "amount" NUMBER(10, 2);